### ISSUE TITLE
IMG file loading error

### ISSUE THREAD

**Issue by LMJayasundara** [bakoushin/self-driving-car-javascript#1]
I am trying to loading IMG file for the train.js
It shows cannot identify the directory
please let me know how to load that file.

I also try to cop my simulator file into the desktop. but also it not work
![Uploading Annotation 2020-06-18 030257.jpg…]()

Great work!!!!
Thank you

**Comment by LMJayasundara** [comment]
/nodejs.org/api/cli.html#cli_unhanode train.js --data C:/Users/SHAN/Desktop/Tensor/Data --epochs 5 --model C:/Users/SHAN/Desktop/Tensor/model
Overriding the gradient for 'Max'
Overriding the gradient for 'OneHot'        
Overriding the gradient for 'PadV2'
Overriding the gradient for 'SpaceToBatchND'
Overriding the gradient for 'SplitV'
2020-06-18 03:18:47.658620: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Epoch 1 / 5
(node:1984) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\SHAN\Desktop\Tensor\ C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_44_721.jpg'
(node:1984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process 
with a non-zero exit code.
(node:1984) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\SHAN\Desktop\Tensor\ C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_44_721.jpg'
(node:1984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1984) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:1984) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\SHAN\Desktop\Tensor\ C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_44_721.jpg'
(node:1984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by bakoushin** [comment]
Could you please share a few first lines of `driving_log.csv` generated by the simulator?

**Comment by LMJayasundara** [comment]
C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\center_2020_05_03_11_51_44_721.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_44_721.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_44_721.jpg, 0, 0, 0, 7.838477E-05
C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\center_2020_05_03_11_51_45_471.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_45_471.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_45_471.jpg, 0, 0, 0, 7.862586E-05
C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\center_2020_05_03_11_51_45_783.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_45_783.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_45_783.jpg, 0, 0, 0, 7.828791E-05
C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\center_2020_05_03_11_51_45_880.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_45_880.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_45_880.jpg, 0, 0, 0, 7.934251E-05
C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\center_2020_05_03_11_51_45_993.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_45_993.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_45_993.jpg, 0, 0, 0, 7.79378E-05
C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\center_2020_05_03_11_51_46_131.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_46_131.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_46_131.jpg, 0, 0, 0, 7.823821E-05
C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\center_2020_05_03_11_51_46_647.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_46_647.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_46_647.jpg, 0, 0, 0, 8.101902E-05
C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\center_2020_05_03_11_51_46_748.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\left_2020_05_03_11_51_46_748.jpg, C:\Users\SHAN\Desktop\simulator-windows-64\Data\IMG\right_2020_05_03_11_51_46_748.jpg, 0, 0, 0, 7.787524E-05

**Comment by bakoushin** [comment]
Could you please explain the environment you are using to run the script?
What is `/nodejs.org/api/cli.html#cli_unhanode`?

**Comment by LMJayasundara** [comment]
nodejs v12.18.0
npm 6.14.4

**Comment by LMJayasundara** [comment]
do you have any solution

**Comment by bakoushin** [comment]
Now it should be fixed. Feel free to reopen otherwise.
Thanks for reporting this issue.

**Comment by LMJayasundara** [comment]
Thank you..

**Comment by LMJayasundara** [comment]
Now it's working.
can you add the IMG data path in the separate directory without using a
simulator directory?
can you modify your code in the above way???

Thank you for your great help.

**Comment by bakoushin** [comment]
Why do we need this?
The IMG path is generated by the simulator and this is the exact path where the image is stored.

**Comment by LMJayasundara** [comment]
we can store the IMG folder in the same Code folder.
It is easy to handle the code.

**Comment by LMJayasundara** [comment]
If you can remove the head path of the load png image that  would be work.
I try to do that.
but ima fail.
please can you help me?

I am using that

var path = require('path');

var filename = path.basename('/Users/Refsnes/demo_path.js');
console.log(filename);
Run example »
<https://www.w3schools.com/nodejs/shownodejs_cmd.asp?filename=demo_met_path_basename>

**Comment by bakoushin** [comment]
If you want to construct a specific path, use `path.join()`. Example:
```javascript
const path = require('path');
const initialPath = 'C:\\Users\\SHAN\\Desktop\\simulator-windows-64\\Data\\IMG\\center_2020_05_03_11_51_46_131.jpg';
const filename = path.basename(initialPath);
const newPath = path.join(__dirname, 'IMG', filename);
console.log(newPath);
```

**Comment by LMJayasundara** [comment]
Thank you...
how to add this part you train.js code
☺

**Comment by bakoushin** [comment]
Why won't you do it yourself? 😄  
That could be a good PR!

Nevertheless, here are the changes: https://github.com/bakoushin/self-driving-car-javascript/blob/relative-path/train.js#L34-L42
Just checkout branch named `relative-path`.

What it does: instead of using absolute paths to the images stored in `driving-log.csv`, it assumes now that images are stored in the `IMG` directory within the `data` directory we've supplied to the script. 
So now we can move data directory anywhere we want, everything should work.

I hope this is what you are looking for.

**Comment by LMJayasundara** [comment]
yeaaaaaaaaaaaaaaaaaaaa...
thank you sooooooooooooooooooooo much,...😍☺😍

**Comment by LMJayasundara** [comment]
Can I connect Carla simulator in a similar way?

**Comment by LMJayasundara** [comment]
I connected carala with js.
But I cannot control it

var net = require('net');

var client = new net.Socket();
client.connect(2000, 'localhost', function() {
    console.log('Connected');
    client.setTimeout(10.0);
});

**Comment by bakoushin** [comment]
I don't know. Could you provide a link to Carla simulator?

**Comment by LMJayasundara** [comment]
Yes of course.
https://carla.org/
This is Carla simulator web page.
It is a python based simulator environment.

I just download the Carla simulator then opened exe file and run js code
ant it was connected. 😍😍
As I mention earlier.

It has some python code for simulated a car in that environment.
So have a very straightforward youtube video that describes how to simulate
a car in that environment in python.

simulate video -
https://www.youtube.com/watch?v=2hM44nr7Wms&list=PLQVvvaa0QuDeI12McNQdnTlWz9XlCa0uo&index=3&t=0s
playlist -
https://www.youtube.com/playlist?list=PLQVvvaa0QuDeI12McNQdnTlWz9XlCa0uo

also, this is very useful to get an idea -
https://carla.org/2018/07/30/release-0.9.0/

If we can develop this environment using Js it will very useful for a
simulate big project with TensorFlow Js.💪💪

**Comment by LMJayasundara** [comment]
Did you get an idea?☺

**Comment by LMJayasundara** [comment]
I also tried to implement a speed based steering angle correction with
udacity simulator

**Comment by LMJayasundara** [comment]
can you get any solution?
I try but I can not get solution🤕🤕

**Comment by bakoushin** [comment]
Thanks for providing the information about Carla.

It is way more advanced than the Udacity simulator in terms of the complexity of simulated word and control APIs as well. 
In short, this project would not work with Carla unless it is completely re-implemented for it.

Since the Carla environment is way rich that Udacity one, more sophisticated models may be required to correctly drive a car. And when it comes to experimenting with different models, the Python infrastructure is the natural choice given the abundance of established tools and libraries, TensorFlow included.

**Comment by LMJayasundara** [comment]
okay, Thank you for your advice☺💪

**Comment by LMJayasundara** [comment]
I am trying to get an image from the camera and create a CSV file like that
Udasity simulator. Also, get steering and throttle(But not now)
This way I can train a real wold robot car.😁

This way create a CSV file
But it can not include any data it always empty.
Please show me the error I did

const cv = require('/opncvnode/node_modules/opencv4nodejs');
const fs = require('fs');
const csv = require('fast-csv');
const ws = fs.createWriteStream('test.csv');

var sec = 0;
var frameRate = 0.5;
var count = 1;

var cap = new cv.VideoCapture(0);

function getFrame(sec){
    cap.set(cv.CAP_PROP_POS_MSEC, sec*1000);
    var frame = cap.read();

    cv.imwrite("image/center_cam" + count + ".jpg", frame);

    cv.imshow('',frame);
    cv.waitKey(1);


///////////////////////////////////////////////////////////////////////////////////////

    var image = "center_cam"+count+".jpg";
    var steering = 0;
    var throttle = 0;

    console.log(image, steering, throttle);

    var data = [{image, steering, throttle}];

    csv.write(data, { headers: true })
    .pipe(ws);


///////////////////////////////////////////////////////////////////////////////////////

    return frame;
};

var success = getFrame(sec);

while(success = true){
    var count = count + 1;
    var sec = sec + frameRate;
    var sec = Math.round(sec);
    var success = getFrame(sec);
};



This way create a CSV file also write data

for (i=0; i<10; i++){

var num1 = Math.random();
var num2 = Math.random();
var add = num1 + num2;

var data = [{num1, num2, add}];

csv.write(data, { headers: true })
.pipe(ws);

}

**Comment by LMJayasundara** [comment]
But it also gets wrong type data format

num1,num2,add
0.7260764056613853,0.2969767742939857,1.023053179955371num1,num2,add
0.9313625225535354,0.7464783328796931,1.6778408554332285num1,num2,add
0.9055004970764169,0.7301077704172396,1.6356082674936565num1,num2,add
0.18310182726664648,0.2515544687958069,0.4346562960624534num1,num2,add
0.9159285448265637,0.5768440038442426,1.4927725486708063num1,num2,add
0.7040326362130156,0.7418406729086742,1.4458733091216898num1,num2,add
0.7971635785667379,0.5465111704901595,1.3436747490568974num1,num2,add
0.8682385206885539,0.03586618439733935,0.9041047050858932num1,num2,add
0.010650019081321904,0.561125578450826,0.5717755975321479num1,num2,add
0.7253343112313102,0.642651626168383,1.3679859373996932

**Comment by LMJayasundara** [comment]
I also ask StackOverflow and GitHub but I can not get solution for that
Please please send me what I did wrong.

Thank you

😃

**Comment by bakoushin** [comment]
I believe since you are wrtiting to a [Writable Stream](https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options) you want to use [writeToStream](https://c2fo.io/fast-csv/docs/formatting/methods#writetostream)

**Comment by LMJayasundara** [comment]
const csv = require('fast-csv');
const csvStream = csv.format();

const fs = require('fs');
const ws = fs.createWriteStream('test.csv');

csvStream.pipe(ws).on('end', () => process.exit());


for(i = 0; i<10; i++){
    var image = 'center'+i+'.jpg';
    var steering = 0;
    csvStream.write({ image, steering });
}

csvStream.end();

I write this way it works!!!

But I can not include this to the main code it shows empty CSV file

**Comment by LMJayasundara** [comment]
my main code

const cv = require('/opncvnode/node_modules/opencv4nodejs');

const csv = require('fast-csv');
const csvStream = csv.format();

const fs = require('fs');
const ws = fs.createWriteStream('test.csv');

csvStream.pipe(ws).on('end', () => process.exit());

var sec = 0;
var frameRate = 0.5;
var count = 1;

var cap = new cv.VideoCapture('video.mp4');

function getFrame(sec){

    cap.set(cv.CAP_PROP_POS_MSEC, sec*1000);
    var frame = cap.read();

    var img_dir = "image/";
    var img_name = "center_cam"+ count +".jpg";

    var image = img_dir + img_name;
    cv.imwrite(image, frame);

    ///////////////////////////////////////////////////////////////////

    var steering = 0;
    csvStream.write({ img_name, steering });

    ///////////////////////////////////////////////////////////////////

    cv.imshow('', frame);
    cv.waitKey(1);

    return frame;

};

var success = getFrame(sec);

while(success = true){
    var count = count + 1;
    var sec = sec + frameRate;
    var sec = Math.round(sec);
    var success = getFrame(sec);
};

csvStream.end();

**Comment by bakoushin** [comment]
This could happen because your code is failing with some error somewhere. I suggest checking console output and getting rid of these errors first.

Some ideas:
Probably you want to check if `frame.empty` before proceed.
Also, isn't that condition `while(success = true)` a typo?

**Comment by LMJayasundara** [comment]
okay thank you so much I will check💪😍

**Comment by LMJayasundara** [comment]
Finally I did it..💪😃😍💪😍

**Comment by LMJayasundara** [comment]
Can I do image augmentation with Javascript/NodeJs like zooming change
brightness and panning images

**Comment by bakoushin** [comment]
Totally.
If you are using OpenCV just apply the same techniques people use in Python.
There are also interesting Node.js packages for image processing:
https://github.com/lovell/sharp
https://www.npmjs.com/package/jimp

**Comment by LMJayasundara** [comment]
okay, thank you very much.
I am using opencv4nodejs😍

I have another question😁

Can I generate the preprocessed images (like zooming flipping images) to
feed and train the algorithm without saving the disk.

Act like as an image augment generator

**Comment by bakoushin** [comment]
Yes. Just preprocess the image before returning it from generator 😄 
Note that preprocessing will significantly slower the training.

**Comment by LMJayasundara** [comment]
Yep. I agree with you. But I am trying to train the algorithm using only
center camera images.
So I need an image generator to get better output from the algorithm even
it slower training... I know you already know it 😂😆
I had a code with image preprocessing.generator.
This is my code for image generator.👇
I think it better to include inside generator function.
But I can not find to way include this in your code.
Please help me😃


const cv = require('/opncvnode/node_modules/opencv4nodejs');

function zoom(image){
    var col = image.cols;
    var row = image.rows;

    var center = new cv.Point((col-1)/2.0, (row-1)/2.0);
    var mat = new cv.getRotationMatrix2D(center, 0, 1.5);
    var zoom_img = image.warpAffine(mat, new cv.Size(col, row));

    return zoom_img;
}

function brightness(image){
    var bright_img = image.mul(0.6);
    return bright_img;
}

function pan(image){
    var top = Math.floor(Math.random() * 20) + 1;
    var bottom = Math.floor(Math.random() * 20) + 1;
    var left = Math.floor(Math.random() * 20) + 1;
    var right = Math.floor(Math.random() * 20) + 1;

    const color = new cv.Vec(0, 0, 0);

    const pan_image = image.copyMakeBorder(top, bottom, left, right, cv.
BORDER_CONSTANT, color);

    return pan_image;
}

function flip(image){
    var flip_img = image.flip(1);
    return flip_img;
}


function imageAugmentation(image){
    var image = cv.imread('center_cam.png');

    if (Math.random() * 1 > 0.5) var image = zoom(image);
    if (Math.random() * 1 > 0.5) var image = brightness(image);
    if (Math.random() * 1 > 0.5) var image = pan(image);
    if (Math.random() * 1 > 0.5) var image = flip(image);

    return image;
}

var image = imageAugmentation(image);

cv.imshowWait('', image);

**Comment by LMJayasundara** [comment]
"Yes. Just preprocess the image before returning it from generator 😄  "
Thank you for your advise 👆 I did it thank you very much...

But I am getting preprocess image as a variable...
Then how it converts to an array buffer

var image = imageAugmentation(image); // output preprocess image as Mat

// console.log(image);

var processImageBuffer = fs.promises.read(image); <= This not work I am
tring diferant way but not work

yield [await centerImageBuffer, Number(steering)];
yield [await processImageBuffer, Number(steering)];



Please please give me an advice..
Thank you

**Comment by LMJayasundara** [comment]
Also, I did this way but it get an error

 var image = imageAugmentation(image);

// console.log(image);

var processImageBuffer = new ArrayBuffer(image);

yield [await centerImageBuffer, Number(steering)];
yield [await processImageBuffer, Number(steering)];

Error

(node:50600) UnhandledPromiseRejectionWarning: Io::Imdecode - expected arg
0 to be a Buffer of Uint8 Values
(node:50600) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was not
handled with .catch(). To terminate the node process on unhandled
promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
(rejection id: 1)
(node:50600) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not
handled will terminate the Node.js process with a non-zero exit code.

**Comment by bakoushin** [comment]
Check what exact types each part of your program is expecting. For example, if some function expects a Buffer, do not feed it with Promise. Make sure it's a Buffer. The same goes for image formats. For instance, my training code expects to get a JPEG image. So you may want either return a JPEG after augmentation or change the code to consume a raw Buffer.
In all that concerns input types, the documentation is your friend.
Also, make sure that augmentation yields images with the same dimensions.

**Comment by LMJayasundara** [comment]
okay... thank you

**Comment by LMJayasundara** [comment]
Hi,
I need help from you.
I developed a semantic segmentation model with Tensorflow Js
But it not reduce acc in training.
Can you help me to fix it😍😍

**Comment by LMJayasundara** [comment]
I think it will help for Javascript self-driving car projects💟
